
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend-final
    username: postgres
    password: passwd
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-handlers-package: cn.edu.bupt.backendfinal.handler
server:
  port: 34948
