
spring:
  datasource:
    url: jdbc:postgresql://172.19.71.71:5432/backend-final
    username: postgres
    password: passwd
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always
